networks:
  internal-network:
    name: internal-network
services:
  # api:
  #   build: ./api
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     # - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #     - PORT=3000
  #   networks:
  #     - internal-network
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   networks:
  #     - internal-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # MONGO_INITDB_DATABASE: recipes
    volumes:
    #  - ./db:/docker-entrypoint-initdb.d/:ro
    #  - ./data:/data/db
    networks:
     - internal-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
     - internal-network