networks:
  internal-network:
    name: internal-network
services:
  ui:
    build: ./ui
    container_name: ui
    networks:
      - internal-network
    restart: always
    volumes:
      - ./ui/nginx/:/etc/nginx/conf.d
    ports:
      - '80:80'
    command: /bin/sh -c "nginx -g 'daemon off;'"
  api:
    container_name: api
    build: ./api
    restart: always
    # ports:
    #   - 80:5000
    depends_on:
      - mongo
    environment:
      DB_CONN_STRING: ${DB_CONN_STRING:-mongodb://mongo:27017/},
      DB_NAME: ${DB_NAME:-challange},
      RECIPE_COLLECTION_NAME: ${RECIPE_COLLECTION_NAME:-recipe},
      CURATION_COLLECTION_NAME: ${CURATION_COLLECTION_NAME:-curation},
    networks:
      - internal-network
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      # MONGO_INITDB_DATABASE: ${DB_NAME:-challange}
    # for local development
    ports:
      - "27017:27017"

    # volumes:
    #  - ./db:/docker-entrypoint-initdb.d/:ro
    #  - ./data:/data/db
    networks:
     - internal-network
  mongo-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: ${DB_CONN_STRING:-mongodb://mongo:27017/}
    networks:
     - internal-network